name: Workflow Filters and Activities

on:
  workflow_dispatch:
  schedule:
    - cron: "*/59 * * * *"
  push:
    branches:
      - main
    # branches-ignore:
    #   - 'feature/*'
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executed for event ${{ github.event_name }}"
